version: "3"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/recordstudio
      - JWT_SECRET=your_jwt_secret
      - AWS_ACCESS_KEY_ID=your_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
      - AWS_REGION=your_aws_region
      - AWS_S3_BUCKET=your_s3_bucket
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./temp:/app/temp

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
